databases:
  - name: chat
    databaseName: chat
    user: chat

services:
  - type: web
    name: chat
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false